nfsops.py: fix 4.18.x (rocky 8.9 kernel) splice_read missing probe
Rocky Linux 8.9 default kernel (4.18.x) produced this error:
ERROR: 2024-09-01 18:57:28 | nfsops | Failed to attach BPF program b'trace_nfs_file_splice_read' to kprobe b'nfs_file_splice_read', it's not traceable (either non-existing, inlined, or marked as "notrace"). Do you have any mounts?

So condition on the kprobe attachment existence of the symbol.

Signed-off-by: Sagi Grimberg <sagi@grimberg.me>